language: node_js
node_js:
- '6.1'
deploy:
  provider: heroku
  api_key:
    secure: gSGPxITrAVQxQDKnYAoKHpVcfmYvq5R1YeEcNte/gh+EyRgzgRCN4lUxtFL0g50S1yebvQHVHLxqmnn97idZdNBtudj/pwCdcIzRql2wJwJcRrYA0Lx5Bbl+D8LqVLhp1bISOREk3KV6YYlzH2DItc5If9MPkbmEJYc7AQjwOZirsN4Vl/v5eqIaxNbC8e1QZSy7+3gfGxDY0EqaE6/oMk5tFZ1ipcq/5MOWEu8lhJ68W+vxtLNiohawrvVWqS7QPGp7NlxKDiTZuXeNnsveR4GLXZC2rfQwrYX8E4nQZ9Q58duCr0FqJRbVYB/8biB8XHXCblrpOknVQt9mWuhAbytgMsVpOHY69d9RieCDGVMnt8PWzy6/p0wTmmvftBmXws5uRdC8YIb+Vnhx4lu+jmBSJDVD4MAom9lWM8eFBL2dTnQJRxQjXqhVuaDdikN2HrSYxOY416MPYcE+iR2k6WpFsetbloRk7pXZMLcfZ7n18IRFRQHueM5TlTXc92Gl5IFI08PR08SNXOP2iF6XtiNfOuDPJurjDNQEIGSrOFbsEdq+z7yGHwqchZtmAcXcZtaDbTf6V+ckCR6ss3Z6bTOHJawlNTnlTbYLHFBzcuT05Bw2XDtI9Q6gKXhJ+XVFooGs5kL+1Yi8Y+HfsLvW4magSS63VOgKnEY3IdY33nM=
  app: the-nodejs-heroku-challenge
